### ISSUE TITLE
Error on running "run_and_log"

### ISSUE THREAD

**Issue by pzonouz** [kaiwan/seals#5]
./build_SEALS.sh: line 48: ./build.config: No such file or directory
build_SEALS.sh: source failed! ./build.config missing or invalid?
It seems build.config is symbolic link to other file that never exist!!
Where is "build.config.vexpress" ?

**Comment by kaiwan** [comment]
Hi, apologies!
I missed seeing the first message until now.
Have made a fix; pl retry and let me know if it works now
