### ISSUE TITLE
TODO: auto-download kernel + busybox src based on version

### ISSUE THREAD

**Issue by kaiwan** [kaiwan/seals#6]
Why have the end-user do this... it should be automated!

**Comment by paranlee** [comment]
I think something example like `docker run seals:armv7-linux-v6.x.y-busybox-v1.a.b` would be nice.
Linux kernel Source files v6.x.y [Linux kernel version history - Wikipedia](https://en.wikipedia.org/wiki/Linux_kernel_version_history) 
and busybox v1.a.b [Source](https://git.busybox.net/busybox/) cached on docker image.

How do you think about below.

Linux Kernel Source Download Automation
```
~$ LINUX_TAG=`curl https://api.github.com/repos/torvalds/linux/git/refs/tags | grep '"ref":' | awk '{print $2}' | tr -d '",\,' | sort -V | tail -1`
~$ echo $LINUX_TAG
refs/tags/v6.0-rc1
~$ curl -O https://github.com/torvalds/linux/archive/$LINUX_TAG
```

BUSYBOX Source Download Automation
```
~$ BUSYBOX_VER=`curl https://busybox.net/downloads/ | grep -Po '(?<=href=")[^"]*' | grep "tar.bz2$" | sort -V | tail -3 | head -1`
~$ echo $BUSYBOX_VER
busybox-1.35.0.tar.bz2
~$  curl -O https://busybox.net/downloads/$BUSYBOX_VER
```

Also, Each Version Selection UI would be nice feature. 

Automated `docker build`, The image size may be large, but I think it will be useful for many people who are in a hurry.

**Comment by kaiwan** [comment]
Done with rel v0.2; see the install.sh script (keeps it simple, no nedd for Docket etc). Closing
