### ISSUE TITLE
"run_and_log" script doesn't boot the kernel while running qemu-system-aarch64 

### ISSUE THREAD

**Issue by Hussain1811** [kaiwan/seals#9]
[Mon_18Sep2023_07:23:29.550999406]
RUN: Running qemu-system-aarch64 now ...
DTB_BLOB_IMG =
[Mon_18Sep2023_07:23:29.566158229] qemu-system-aarch64 -m 512 -M vexpress-a15                   -cpu max -smp 4,sockets=2 -cpu cortex-a15                       -kernel /root/qemu/seals/SEALS_staging/SEALS_staging_vexpress/images/Image.gz                         -drive file=/root/qemu/seals/SEALS_staging/SEALS_staging_vexpress/images/rfs.img,format=raw,id=drive0                   -append "console=ttyAMA0 root=/dev/mmcblk0 init=/sbin/init" -nographic -no-reboot

Ok? (after pressing ENTER, give it a moment ...)

Also, please exit by properly shutting down:
use the 'poweroff' command to do so.
(Worst case, typing Ctrl-a-x (abruptly) shuts Qemu down).

 [Press ENTER to continue, or Ctrl-C to abort now...]

ALSA lib pcm_dmix.c:1032:(snd_pcm_dmix_open) unable to open slave
alsa: Could not initialize DAC
alsa: Failed to open `default':
alsa: Reason: No such file or directory
ALSA lib pcm_dmix.c:1032:(snd_pcm_dmix_open) unable to open slave
alsa: Could not initialize DAC
alsa: Failed to open `default':
alsa: Reason: No such file or directory
audio: Failed to create voice `lm4549.out'

**Comment by Hussain1811** [comment]
Basically, the QEMU bash command prompt isn't up

**Comment by Hussain1811** [comment]
However with arm, there is a stuck at the below error in addition to the ALSA related errors
`env: can't execute '/bin/bash': No such file or directory`

**Comment by Hussain1811** [comment]
Kernel Version: 6.1.53
BusyBox Version: 1_36_stable

**Comment by kaiwan** [comment]
Hi @Hussain1811 
thanks for your report.

> [Mon_18Sep2023_07:23:29.550999406] RUN: Running qemu-system-aarch64 now ... DTB_BLOB_IMG = 
This seems to be the issue i think... the DTB must be present (for ARM 32/64)... 
I'll investigate when i get time. On my system, the DTB image is populated and it ran fine..

[Mon_18Sep2023_07:23:29.566158229] qemu-system-aarch64 -m 512 -M vexpress-a15 -cpu max -smp 4,sockets=2 -cpu cortex-a15 -kernel /root/qemu/seals/SEALS_staging/SEALS_staging_vexpress/images/Image.gz -drive file=/root/qemu/seals/SEALS_staging/SEALS_staging_vexpress/images/rfs.img,format=raw,id=drive0 -append "console=ttyAMA0 root=/dev/mmcblk0 init=/sbin/init" -nographic -no-reboot
> 
> Ok? (after pressing ENTER, give it a moment ...)
> 
> Also, please exit by properly shutting down: use the 'poweroff' command to do so. (Worst case, typing Ctrl-a-x (abruptly) shuts Qemu down).
> 
> [Press ENTER to continue, or Ctrl-C to abort now...]
> 
> ALSA lib pcm_dmix.c:1032:(snd_pcm_dmix_open) unable to open slave alsa: Could not initialize DAC alsa: Failed to open `default': alsa: Reason: No such file or directory ALSA lib pcm_dmix.c:1032:(snd_pcm_dmix_open) unable to open slave alsa: Could not initialize DAC alsa: Failed to open `default': alsa: Reason: No such file or directory audio: Failed to create voice `lm4549.out'

**Comment by kaiwan** [comment]
Hi @Hussain1811 ,

Can you pl run this:
sudo bash -x ./run-qemu.sh 0 >rep 2>&1

Then, press Enter, let it run a few seconds, then press Ctrl+a+x
U should get back the prompt;.
Pl send the content of the 'rep' file...

Thanks, kaiwan.

**Comment by Hussain1811** [comment]
Hello @kaiwan 

Sent the contents of rep file over mail. Please check.

Regards
Sadiq

**Comment by kaiwan** [comment]
Great (though u can attach it here itself & then we have a full record...).

So, i need more info, pl verify:
1. the build.config ; do an ls -l on it; it should be a soft link like this; pl check:
 build.config -> build.config.arm64_rpi3b
2. grep DTB build.config  # pl copy-paste the output

**Comment by Hussain1811** [comment]
root@bapvedev014:~/qemu/seals# ls -l build.config
lrwxrwxrwx 1 root root 27 Sep 18 23:17 build.config -> build.config.arm32_vexpress

root@bapvedev014:~/qemu/seals# grep DTB build.config
# DTB: specify the Device Tree Blob <filename>.dtb
DTB_BLOB=vexpress-v2p-ca15_a7.dtb

**Comment by kaiwan** [comment]
Ah, so there's the problem!
Pl see inline below...

On Tue, Sep 19, 2023 at 1:08 PM Hussain ***@***.***> wrote:
>
> ***@***.***:~/qemu/seals# ls -l build.config
> lrwxrwxrwx 1 root root 27 Sep 18 23:17 build.config -> build.config.arm32_vexpress

This is the config for the ARM *32* bit not the ARM 64... hence it's failing.
You need to first setup the soft link correctly, having the
build.config symlink point to the correct config file;
here its the file build.config.arm64_rpi3b.
(As is explained here https://github.com/kaiwan/seals/wiki/SEALs-HOWTO step 4).

Do:
cd <your-seals-dir>
ln -sf build.config.arm64_qemuvirt build.config

Build it:
./build_SEALS.sh

and have it run; it should work now...

Pl let me know,

T&R,
Kaiwan.

**Comment by Hussain1811** [comment]
Thanks for the suggestions. The boot-up starts. But, i don't see the prompt due to below error:
`env: can't execute '/bin/bash': No such file or directory`

**Comment by kaiwan** [comment]
I see...
Pl try this:
edit the build.config (in effect the one it points to) changing this line
SHELL2RUN=/bin/bash
to this
SHELL2RUN=/bin/sh

Rebuild, retry...
Thx.

**Comment by Hussain1811** [comment]
Perfect!!!
This works now.

Thanks a lot @kaiwan 
Closing the issue

**Comment by kaiwan** [comment]
:-)    Good.

Thanks for raising this... it will help improve the project!
